name: chekcsums
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  path: ^1.9.0
  filesystem_picker: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true